insert into state_image(id, state_id, algorithm_position, picture) values
(1, 8, '1', '/images/states/HS_1.png'),
(2, 9, '2', '/images/states/HS_2.png'),
(3, 10, '3', '/images/states/HS_3.png'),
(4, 11, '3B*', '/images/states/HS_3_1.png'),
(5, 12, '4', '/images/states/HS_4.png'),
(6, 13, '4A', '/images/states/HS_5.png'),
(7, 14, '6', '/images/states/HS_6.png'),
(8, 15, 'Exercise stress echocardiography test', '/images/states/HS_8.png'),
(9, 17, 'Psychodiagnostics', '/images/states/HS_10.png'),
(10, 18, 'Psychodiagnostics', '/images/states/HS_10.png'),
(11, 19, 'Psychotherapy, psychotropic drugs ', '/images/states/HS_11.png'),
(12, 1, '1', '/images/states/HSt_1.png'),
(13, 2, '2B', '/images/states/HSt_2.png'),
(14, 3, 'Optimal Medical Therapy CAD, AAT, CA, ICD', '/images/states/HSt_3.png'),
(15, 4, 'Optimal Medical Therapy CAD, AAT, CA, ICD', '/images/states/HSt_4.png'),
(17, 5, 'Beta-blockers', '/images/states/HSt_5.png'),
(18, 6, 'Optimal Medical Therapy CAD, AAT, CA, ICD', '/images/states/HSt_6.png');